remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: An Introduction to Quantum Computing for Business
description: Everything you need to know about quantum technology in a free compact guide. 
