title: QC For Business
description: Replace this description please. 
theme: just-the-docs

url: https://koengr.github.io/QCforBusiness

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
